### ISSUE TITLE
Modal window

### ISSUE THREAD

**Issue by eko24ive** [Oksana-Shuliak/Class-work-6#1]
First of all, be sure that your network tab in DevTool looks similar to this:
![image](https://cloud.githubusercontent.com/assets/25591824/23118361/81fb5a32-f75c-11e6-962f-849f236c4d53.png)

In network tab you can check if all your files are loaded.

According to your code only this button will launch a modal
```html
<button type="button" class="btn btn-primary btn-lg" data-toggle="modal" data-target="#myModal">Launch demo modal</button>
```

Because of `data-toggle` and `data-target` attributes.

Also clearing cache of your browser may help you - https://en.wikipedia.org/wiki/Wikipedia:Bypass_your_cache#Google_Chrome

**Comment by Oksana-Shuliak** [comment]
I have no **jquery-2-2-4.min.js** and **bootstrap.js** 
![image](https://cloud.githubusercontent.com/assets/25491466/23166611/f8d37a0c-f849-11e6-9319-e7e59ffa71f4.png)
I've cleared cash but nothing changed

**Comment by eko24ive** [comment]
Try to replace your `<script>` blocks at the end of the element with theese:
```html
	<script type="text/javascript" src="https://code.jquery.com/jquery-2.2.4.min.js"></script>
    <script type="text/javascript" src="./bootstrap-3.3.7-dist/js/bootstrap.js"></script>
```

**Comment by Oksana-Shuliak** [comment]
They were at the end. 
![image](https://cloud.githubusercontent.com/assets/25491466/23167958/1e2aaf64-f84f-11e6-8cff-a1e3e0900c9d.png)
I just copied your <script> blocks and it's finaly works. Thanks)
![image](https://cloud.githubusercontent.com/assets/25491466/23167864/bcc95cac-f84e-11e6-8a91-4798e1656ec8.png)

**Comment by eko24ive** [comment]
Good,
Perhaps there was some invisible symbol in your code.
Feel free to close issue if it's solved

**Comment by Oksana-Shuliak** [comment]
everything is ok
